services:
  postgres:
    image: postgres:15
    container_name: si-postgres
    restart: always
    environment:
      POSTGRES_USER: siuser
      POSTGRES_PASSWORD: sipassword
      POSTGRES_DB: sidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
